# Generated by Django 3.2.5 on 2021-07-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=3)),
                ('work_order', models.CharField(max_length=100)),
                ('serial_num', models.CharField(max_length=100)),
                ('part_num', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
