# Generated by Django 3.2.5 on 2021-08-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='email',
            field=models.EmailField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='part_num',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='task',
            name='serial_num',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='task',
            name='work_order',
            field=models.CharField(max_length=10),
        ),
    ]
