# Generated by Django 3.2.5 on 2021-08-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210802_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ_Vibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='email',
            field=models.EmailField(max_length=25),
        ),
    ]
