# Generated by Django 3.2.5 on 2021-08-11 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20210811_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='emp_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resources',
            name='res_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resources',
            name='status',
            field=models.CharField(choices=[('prod', 'PRODUCTION'), ('eng', 'ENG-ONLY'), ('cal', 'Out of Cal'), ('down', 'Resource-Down')], default='prod', max_length=25),
        ),
    ]
