# Generated by Django 3.2.5 on 2021-08-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210811_0505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resources',
            old_name='resource',
            new_name='resource_name',
        ),
        migrations.AddField(
            model_name='employees',
            name='task_history',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='resources',
            name='assigned_tasks',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
